version: '3.7'
services:
  api:
    container_name: poll_api_service
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    container_name: poll_mongo_service
    image: mongo:4.0.4
    restart: always
    command: mongod --port ${MONGO_PORT} --bind_ip_all
    env_file:
      - .env
    volumes:
      - ~/.volumes/poll/mongo-data:/data/db
  mongo-express:
    container_name: poll_mongo_express_service
    image: mongo-express
    restart: always
    ports:
      - 6969:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo
